### ISSUE TITLE
卸载后无法还原

### ISSUE THREAD

**Issue by dzylikecode** [TheSecondAkari/vscode-background-widthsidebar#1]
不想使用了，卸载后背景还是没变，希望能还原回原来的背景

**Comment by dzylikecode** [comment]
我知道了，先配置为"background.useDefaultAsoul": false,然后卸载就可以了

**Comment by TheSecondAkari** [comment]
也可以配置 background.enabled： false   ， 这个配置是插件的整体开关

**Comment by TheSecondAkari** [comment]
我在readme中写的明显一点吧🥰😭😭😭
